In [17]:
import pandas as pd

pd.options.display.max_columns = 100

dtypes = {
    'delivery_type': 'category',
    'addr_region_reg': 'category',
    'addr_region_fact': 'category',
    'channel_name': 'category',
    'channel_name_2': 'category',
    'sas_limit_after_003_amt': 'uint8',
    'sas_limit_last_amt': 'uint8',
    'channel_name_modified_2018': 'category',
    'clnt_education_name': 'category',
    'clnt_marital_status_name': 'category',
    'clnt_speciality_sphere_name': 'category',
    'clnt_sex_name': 'category',
    'prt_name': 'category',
    'clnt_income_month_avg_net_amt': 'uint',
    'clnt_expense_month_avg_amt': 'uint',
    'app_addr_region_reg': 'category',
    'app_addr_region_fact': 'category',
    'app_addr_region_sale': 'category',
    'prt_name': 'category',
    'feature_0': 'category',
    'clnt_birth_year': 'uint',
    'addr_region_fact_encoding1': 'float32',
    'addr_region_fact_encoding2': 'float32',
    'addr_region_reg_encoding1': 'float32',
    'addr_region_reg_encoding2': 'float32',
    'app_addr_region_reg_encoding1': 'float32',
    'app_addr_region_reg_encoding2': 'float32',
    'app_addr_region_fact_encoding1': 'float32',
    'app_addr_region_fact_encoding2': 'float32',
    'app_addr_region_sale_encoding1': 'float32',
    'app_addr_region_sale_encoding2': 'float32',
    'loans_main_borrower': 'float32',
    'loans_active': 'float32',
    'max_overdue_status': 'category',
    'ttl_inquiries': 'uint',
    'ttl_auto_loan': 'bool',
    'ttl_mortgage': 'bool',
    'ttl_credit_card': 'bool',
    'ttl_consumer': 'bool',
    'worst_status_ever': 'category',
    'feature_0': 'category',
    'feature_1': 'uint',
    'feature_2': 'uint',
    'feature_3': 'uint',
    'feature_4': 'uint',
    'feature_5': 'uint',
    'feature_6': 'uint',
    'feature_7': 'uint',
    'fl_coborrower': 'bool',
    'pay_load': 'float32',
    'makro_region': 'category',
    'fo': 'category',
    'region': 'category',
    'feature_30': 'category'
}

fill_missing = [
    ('inquiry_recent_period', 0, 'uint'),
    ('inquiry_1_week', 0, 'uint'),
    ('clnt_experience_cur_mnth', 0, 'uint'),
    ('clnt_experience_total_mnth', 0, 'uint'),
    ('last_loan_date', 6200, 'uint'),
    ('first_loan_date', 6200, 'uint'),
#     ('ttl_bankruptcies', -1, 'category'),
    ('inquiry_recent_period', 0, 'uint'),
    ('inquiry_3_month', 0, 'uint'),
    ('inquiry_6_month', 0, 'uint'),
    ('inquiry_9_month', 0, 'uint'),
    ('inquiry_12_month', 0, 'uint'),
    ('inquiry_1_week', 0, 'uint'),
    ('inquiry_1_month', 0, 'uint'),
#     *[
#         (f'feature_{i}', -1, 'float32')
#         for i in range(10, 30)
#         if i != 11 and i != 26
#     ]
]

cols_to_use = (
    list(dtypes.keys()) +
    list(col for col, *_ in fill_missing) + 
    ['card_id', 'target']
)
    
df = pd.read_csv('../data/train.csv', index_col='card_id', dtype=dtypes, usecols=cols_to_use)

df['missing'] = df.isnull().sum(axis='columns')

for col, fill, dtype in fill_missing:
    df[col] = df[col].fillna(fill).astype(dtype)

df.head()

,target,delivery_type,addr_region_reg,addr_region_fact,channel_name,channel_name_2,channel_name_modified_2018,sas_limit_after_003_amt,sas_limit_last_amt,clnt_education_name,clnt_marital_status_name,clnt_speciality_sphere_name,clnt_income_month_avg_net_amt,clnt_expense_month_avg_amt,clnt_experience_cur_mnth,clnt_experience_total_mnth,clnt_sex_name,app_addr_region_reg,app_addr_region_fact,app_addr_region_sale,prt_name,feature_0,clnt_birth_year,addr_region_fact_encoding1,addr_region_fact_encoding2,addr_region_reg_encoding1,addr_region_reg_encoding2,app_addr_region_reg_encoding1,app_addr_region_reg_encoding2,app_addr_region_fact_encoding1,app_addr_region_fact_encoding2,app_addr_region_sale_encoding1,app_addr_region_sale_encoding2,loans_main_borrower,loans_active,last_loan_date,first_loan_date,max_overdue_status,inquiry_recent_period,inquiry_3_month,inquiry_6_month,inquiry_9_month,inquiry_12_month,ttl_inquiries,ttl_auto_loan,ttl_mortgage,ttl_credit_card,ttl_consumer,worst_status_ever,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,fl_coborrower,pay_load,inquiry_1_week,inquiry_1_month,makro_region,fo,region,feature_30,missing
card_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
cid_10620,1,cat_1,107,107,cat_0,cat_3,cat_0,1,1,cat_1,cat_4,cat_0,3,0,0,0,cat_0,107,107,45,cat_9,cat_7,46,6746.987793,7159.090820,6746.987793,7159.090820,6746.987793,7159.090820,6746.987793,7159.090820,6666.666504,6571.428711,0.88,0.78,193,2851,2,0,7,10,12,19,87,False,False,True,True,3,3,10,4,0,0,5,1,False,0.82,1,3,0,0,0,3,0
cid_105724,0,cat_1,9,9,cat_2,cat_5,cat_2,3,3,cat_1,cat_2,cat_26,5,1,2,3,cat_1,9,9,1,cat_8,cat_9,47,7469.879395,7500.000000,7469.879395,7500.000000,7469.879395,7500.000000,7469.879395,7500.000000,7948.717773,7714.285645,0.77,0.70,73,4288,1,58,19,28,31,43,94,True,False,True,True,2,2,5,0,0,0,0,0,False,0.93,0,0,0,0,0,7,0
cid_101410,1,cat_1,109,109,cat_0,cat_3,cat_0,1,1,cat_1,cat_2,cat_15,2,0,0,0,cat_0,109,109,109,cat_9,cat_10,44,7831.325195,8068.181641,7831.325195,8068.181641,7831.325195,8068.181641,7831.325195,8068.181641,5384.615234,5142.856934,0.51,0.00,242,1852,1,30,6,6,11,20,31,False,False,True,True,2,1,2,0,0,0,0,0,False,0.00,0,2,2,4,71,4,0
cid_38961,0,cat_1,66,66,cat_0,cat_3,cat_0,3,3,cat_1,cat_2,cat_14,2,1,0,0,cat_0,66,66,66,cat_9,cat_7,27,6746.987793,6704.545410,6746.987793,6704.545410,6746.987793,6704.545410,6746.987793,6704.545410,3076.923096,1714.285767,0.28,0.57,868,868,1,366,0,0,0,0,8,False,True,False,False,2,0,4,0,0,0,3,0,True,0.92,0,0,0,0,0,7,0
cid_57462,0,cat_1,16,16,cat_0,cat_3,cat_0,0,0,cat_4,cat_2,cat_24,3,0,0,0,cat_0,16,16,16,cat_9,cat_13,42,7228.915527,7272.727051,7228.915527,7272.727051,7228.915527,7272.727051,7228.915527,7272.727051,4102.563965,3142.857178,0.28,0.00,1525,1525,1,26,4,7,8,15,33,False,False,True,False,1,0,0,0,0,0,0,0,False,0.00,0,3,0,0,0,7,0

In [18]:
class MeanEncoder:
    
    def __init__(self, df, on, by, prior_count=100):
        self.on = on
        self.by = by
        counts = df.groupby(by)[on].agg(['mean', 'count'])
        avg = df[on].mean()
        self.means = (
            counts
            .eval('(mean * count + @avg * @prior_count) / (count + @prior_count)')
            .rename(str(self))
        )
    
    def __str__(self):
        return f'avg_{self.on}_by_{self.by}'
        
    def transform(self, df):
        return df.join(self.means, on=self.by)[self.means.name]

In [19]:
class CountEncoder:
    
    def __init__(self, df, on):
        self.on = on
        self.counts = df.groupby(on).size().rename(str(self))
    
    def __str__(self):
        return f'{self.on}_size'
        
    def transform(self, df):
        return df.join(self.counts, on=self.on)[self.counts.name]

In [20]:
class NMissing:
    
    def __str__(self):
        return 'n_missing'
    
    def transform(self, df):
        return df.isnull().sum(axis='columns').rename(str(self))

In [21]:
extractors = [
    MeanEncoder(df, on='target', by='addr_region_fact'),
    CountEncoder(df, 'app_addr_region_sale_encoding1'),
    CountEncoder(df, 'app_addr_region_sale_encoding2'),
    CountEncoder(df, 'inquiry_recent_period'),
    NMissing(),
    MeanEncoder(df, on='missing', by='addr_region_fact'),
]

In [22]:
features = []

for ex in extractors:
    print(str(ex))
    features.append(ex.transform(df)) 
    
train = pd.concat([df] + features, axis='columns')
train.head()

avg_target_by_addr_region_fact
app_addr_region_sale_encoding1_size
app_addr_region_sale_encoding2_size
inquiry_recent_period_size
n_missing
avg_missing_by_addr_region_fact

,target,delivery_type,addr_region_reg,addr_region_fact,channel_name,channel_name_2,channel_name_modified_2018,sas_limit_after_003_amt,sas_limit_last_amt,clnt_education_name,clnt_marital_status_name,clnt_speciality_sphere_name,clnt_income_month_avg_net_amt,clnt_expense_month_avg_amt,clnt_experience_cur_mnth,clnt_experience_total_mnth,clnt_sex_name,app_addr_region_reg,app_addr_region_fact,app_addr_region_sale,prt_name,feature_0,clnt_birth_year,addr_region_fact_encoding1,addr_region_fact_encoding2,addr_region_reg_encoding1,addr_region_reg_encoding2,app_addr_region_reg_encoding1,app_addr_region_reg_encoding2,app_addr_region_fact_encoding1,app_addr_region_fact_encoding2,app_addr_region_sale_encoding1,app_addr_region_sale_encoding2,loans_main_borrower,loans_active,last_loan_date,first_loan_date,max_overdue_status,inquiry_recent_period,inquiry_3_month,inquiry_6_month,inquiry_9_month,inquiry_12_month,ttl_inquiries,ttl_auto_loan,ttl_mortgage,ttl_credit_card,ttl_consumer,worst_status_ever,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,fl_coborrower,pay_load,inquiry_1_week,inquiry_1_month,makro_region,fo,region,feature_30,missing,avg_target_by_addr_region_fact,app_addr_region_sale_encoding1_size,app_addr_region_sale_encoding2_size,inquiry_recent_period_size,n_missing,avg_missing_by_addr_region_fact
card_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
cid_10620,1,cat_1,107,107,cat_0,cat_3,cat_0,1,1,cat_1,cat_4,cat_0,3,0,0,0,cat_0,107,107,45,cat_9,cat_7,46,6746.987793,7159.090820,6746.987793,7159.090820,6746.987793,7159.090820,6746.987793,7159.090820,6666.666504,6571.428711,0.88,0.78,193,2851,2,0,7,10,12,19,87,False,False,True,True,3,3,10,4,0,0,5,1,False,0.82,1,3,0,0,0,3,0,0.662549,1626,1626,30652,0,0.017536
cid_105724,0,cat_1,9,9,cat_2,cat_5,cat_2,3,3,cat_1,cat_2,cat_26,5,1,2,3,cat_1,9,9,1,cat_8,cat_9,47,7469.879395,7500.000000,7469.879395,7500.000000,7469.879395,7500.000000,7469.879395,7500.000000,7948.717773,7714.285645,0.77,0.70,73,4288,1,58,19,28,31,43,94,True,False,True,True,2,2,5,0,0,0,0,0,False,0.93,0,0,0,0,0,7,0,0.498339,54906,54906,228,0,0.036922
cid_101410,1,cat_1,109,109,cat_0,cat_3,cat_0,1,1,cat_1,cat_2,cat_15,2,0,0,0,cat_0,109,109,109,cat_9,cat_10,44,7831.325195,8068.181641,7831.325195,8068.181641,7831.325195,8068.181641,7831.325195,8068.181641,5384.615234,5142.856934,0.51,0.00,242,1852,1,30,6,6,11,20,31,False,False,True,True,2,1,2,0,0,0,0,0,False,0.00,0,2,2,4,71,4,0,0.434518,2020,2089,3794,0,0.037735
cid_38961,0,cat_1,66,66,cat_0,cat_3,cat_0,3,3,cat_1,cat_2,cat_14,2,1,0,0,cat_0,66,66,66,cat_9,cat_7,27,6746.987793,6704.545410,6746.987793,6704.545410,6746.987793,6704.545410,6746.987793,6704.545410,3076.923096,1714.285767,0.28,0.57,868,868,1,366,0,0,0,0,8,False,True,False,False,2,0,4,0,0,0,3,0,True,0.92,0,0,0,0,0,7,0,0.478198,1616,1592,7355,0,0.026809
cid_57462,0,cat_1,16,16,cat_0,cat_3,cat_0,0,0,cat_4,cat_2,cat_24,3,0,0,0,cat_0,16,16,16,cat_9,cat_13,42,7228.915527,7272.727051,7228.915527,7272.727051,7228.915527,7272.727051,7228.915527,7272.727051,4102.563965,3142.857178,0.28,0.00,1525,1525,1,26,4,7,8,15,33,False,False,True,False,1,0,0,0,0,0,0,0,False,0.00,0,3,0,0,0,7,0,0.525827,6313,6800,370,0,0.032290

In [23]:
train.shape

(90000, 71)

In [24]:
X = train.drop(columns='target')
y = train['target']
X.head()

,delivery_type,addr_region_reg,addr_region_fact,channel_name,channel_name_2,channel_name_modified_2018,sas_limit_after_003_amt,sas_limit_last_amt,clnt_education_name,clnt_marital_status_name,clnt_speciality_sphere_name,clnt_income_month_avg_net_amt,clnt_expense_month_avg_amt,clnt_experience_cur_mnth,clnt_experience_total_mnth,clnt_sex_name,app_addr_region_reg,app_addr_region_fact,app_addr_region_sale,prt_name,feature_0,clnt_birth_year,addr_region_fact_encoding1,addr_region_fact_encoding2,addr_region_reg_encoding1,addr_region_reg_encoding2,app_addr_region_reg_encoding1,app_addr_region_reg_encoding2,app_addr_region_fact_encoding1,app_addr_region_fact_encoding2,app_addr_region_sale_encoding1,app_addr_region_sale_encoding2,loans_main_borrower,loans_active,last_loan_date,first_loan_date,max_overdue_status,inquiry_recent_period,inquiry_3_month,inquiry_6_month,inquiry_9_month,inquiry_12_month,ttl_inquiries,ttl_auto_loan,ttl_mortgage,ttl_credit_card,ttl_consumer,worst_status_ever,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,fl_coborrower,pay_load,inquiry_1_week,inquiry_1_month,makro_region,fo,region,feature_30,missing,avg_target_by_addr_region_fact,app_addr_region_sale_encoding1_size,app_addr_region_sale_encoding2_size,inquiry_recent_period_size,n_missing,avg_missing_by_addr_region_fact
card_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
cid_10620,cat_1,107,107,cat_0,cat_3,cat_0,1,1,cat_1,cat_4,cat_0,3,0,0,0,cat_0,107,107,45,cat_9,cat_7,46,6746.987793,7159.090820,6746.987793,7159.090820,6746.987793,7159.090820,6746.987793,7159.090820,6666.666504,6571.428711,0.88,0.78,193,2851,2,0,7,10,12,19,87,False,False,True,True,3,3,10,4,0,0,5,1,False,0.82,1,3,0,0,0,3,0,0.662549,1626,1626,30652,0,0.017536
cid_105724,cat_1,9,9,cat_2,cat_5,cat_2,3,3,cat_1,cat_2,cat_26,5,1,2,3,cat_1,9,9,1,cat_8,cat_9,47,7469.879395,7500.000000,7469.879395,7500.000000,7469.879395,7500.000000,7469.879395,7500.000000,7948.717773,7714.285645,0.77,0.70,73,4288,1,58,19,28,31,43,94,True,False,True,True,2,2,5,0,0,0,0,0,False,0.93,0,0,0,0,0,7,0,0.498339,54906,54906,228,0,0.036922
cid_101410,cat_1,109,109,cat_0,cat_3,cat_0,1,1,cat_1,cat_2,cat_15,2,0,0,0,cat_0,109,109,109,cat_9,cat_10,44,7831.325195,8068.181641,7831.325195,8068.181641,7831.325195,8068.181641,7831.325195,8068.181641,5384.615234,5142.856934,0.51,0.00,242,1852,1,30,6,6,11,20,31,False,False,True,True,2,1,2,0,0,0,0,0,False,0.00,0,2,2,4,71,4,0,0.434518,2020,2089,3794,0,0.037735
cid_38961,cat_1,66,66,cat_0,cat_3,cat_0,3,3,cat_1,cat_2,cat_14,2,1,0,0,cat_0,66,66,66,cat_9,cat_7,27,6746.987793,6704.545410,6746.987793,6704.545410,6746.987793,6704.545410,6746.987793,6704.545410,3076.923096,1714.285767,0.28,0.57,868,868,1,366,0,0,0,0,8,False,True,False,False,2,0,4,0,0,0,3,0,True,0.92,0,0,0,0,0,7,0,0.478198,1616,1592,7355,0,0.026809
cid_57462,cat_1,16,16,cat_0,cat_3,cat_0,0,0,cat_4,cat_2,cat_24,3,0,0,0,cat_0,16,16,16,cat_9,cat_13,42,7228.915527,7272.727051,7228.915527,7272.727051,7228.915527,7272.727051,7228.915527,7272.727051,4102.563965,3142.857178,0.28,0.00,1525,1525,1,26,4,7,8,15,33,False,False,True,False,1,0,0,0,0,0,0,0,False,0.00,0,3,0,0,0,7,0,0.525827,6313,6800,370,0,0.032290

In [25]:
cat_cols = [col for col in X.dtypes.keys() if str(X.dtypes[col]) == "category"]
print(cat_cols)

['delivery_type', 'addr_region_reg', 'addr_region_fact', 'channel_name', 'channel_name_2', 'channel_name_modified_2018', 'clnt_education_name', 'clnt_marital_status_name', 'clnt_speciality_sphere_name', 'clnt_sex_name', 'app_addr_region_reg', 'app_addr_region_fact', 'app_addr_region_sale', 'prt_name', 'feature_0', 'max_overdue_status', 'worst_status_ever', 'makro_region', 'fo', 'region', 'feature_30']

In [26]:
from sklearn import model_selection

X_fit, X_val, y_fit, y_val = model_selection.train_test_split(
    X, y,
    test_size=.5,
    random_state=42,
    shuffle=True
)

In [27]:
X.columns[39]

'inquiry_6_month'

In [28]:
class top_10_auc(object):

    def get_final_error(self, error, weight=None):
        return error

    def is_max_optimal(self):
        return True

    def evaluate(self, approxes, target, weight=None):
        # approxes - list of list-like objects (one object per approx dimension)
        # target - list-like object
        # weight - list-like object, can be None
        assert len(approxes) == 1
        assert len(target) == len(approxes[0])
        
        approx = approxes[0]
        pred = [0 for i in range(len(target))]
        
        for i in range(len(target)):
            if approx[i] <= 1.1486528:
                pred[i]=0
            if approx[i] > 1.1486528 and approx[i] <= 1.6586176:
                pred[i]=1
            if approx[i] > 1.6586176 and approx[i] <= 2.20792616:
                pred[i]=2
            if approx[i] > 2.20792616:
                pred[i]=3
        
        return qwk(target, pred), 0

In [30]:
import catboost
from scipy import special

fit = catboost.Pool(X_fit, y_fit, cat_features=cat_cols)
val = catboost.Pool(X_val, y_val, cat_features=cat_cols)

model = catboost.CatBoostClassifier(iterations=500,
                                    learning_rate=0.01,
                                    depth=8,
                                    eval_metric='AUC',
                                    random_seed = 42,
                                    bagging_temperature = 0.2,
                                    od_type='Iter',
                                    metric_period = 50,
                                    od_wait=50)

model.fit(fit, 
          use_best_model=True,
          eval_set=val)

Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric.

0:	test: 0.7063983	best: 0.7063983 (0)	total: 135ms	remaining: 1m 7s
50:	test: 0.7208083	best: 0.7208083 (50)	total: 6.53s	remaining: 57.5s
100:	test: 0.7240066	best: 0.7240066 (100)	total: 13.1s	remaining: 51.6s
150:	test: 0.7264457	best: 0.7264457 (150)	total: 19.3s	remaining: 44.6s
200:	test: 0.7285253	best: 0.7285253 (200)	total: 25.8s	remaining: 38.4s
250:	test: 0.7307180	best: 0.7307180 (250)	total: 32.4s	remaining: 32.1s
300:	test: 0.7324872	best: 0.7324872 (300)	total: 38.8s	remaining: 25.7s
350:	test: 0.7336185	best: 0.7336185 (350)	total: 45.6s	remaining: 19.3s
400:	test: 0.7347390	best: 0.7347390 (400)	total: 51.9s	remaining: 12.8s
450:	test: 0.7357046	best: 0.7357046 (450)	total: 58.2s	remaining: 6.32s
499:	test: 0.7364369	best: 0.7364369 (499)	total: 1m 4s	remaining: 0us

bestTest = 0.7364368813
bestIteration = 499

In [32]:
import numpy as np
from sklearn import metrics

y_pred = model.predict_proba(X_val)[:, 1]

def roc_auc_score_at_K(predicted_proba, target, rate=0.1, quantile_inf=0.05, quantile_sup=0.95):      
    predicted_proba = pd.Series(predicted_proba)
    quantile_inf = predicted_proba.quantile(quantile_inf)
    quantile_sup = predicted_proba.quantile(quantile_sup)
    predicted_proba = predicted_proba.apply(lambda x: 10**-6 if x < quantile_sup and x > quantile_inf else x)
    order = np.argsort(-predicted_proba) 
    top_k = int(rate * len(predicted_proba)) 
    return metrics.roc_auc_score(target[order][:top_k], predicted_proba[order][:top_k]) 

val_score = roc_auc_score_at_K(y_pred, y_val)
val_score

0.8983750827043063

In [ ]:
"""
model = catboost.CatBoostClassifier(iterations=2000,
                                    learning_rate=0.01,
                                    depth=10,
                                    eval_metric='AUC',
                                    random_seed = 42,
                                    bagging_temperature = 0.2,
                                    od_type='Iter',
                                    metric_period = 50,
                                    od_wait=50)
"""
0.9039137630360785

In [22]:
model.save_model(f'../track_2_catboost/model.cbm')

import joblib

!rm -f ./track_2/*.pkl

for ex in extractors:
    joblib.dump(ex, f'../track_2_catboost/{ex}.pkl')

In [33]:
from sklearn import model_selection

cv = model_selection.KFold(5, random_state=42)

oof = []

for i, (fit, val) in enumerate(cv.split(X, y)):
    
    X_fit = X.iloc[fit]
    X_val = X.iloc[val]
    
    y_fit = y.iloc[fit]
    y_val = y.iloc[val]
    
    
    fit = catboost.Pool(X_fit, y_fit, cat_features=cat_cols)
    val = catboost.Pool(X_val, y_val, cat_features=cat_cols)

    model = catboost.CatBoostClassifier(iterations=500,
                                        learning_rate=0.01,
                                        depth=10,
                                        eval_metric='AUC',
                                        random_seed = 42,
                                        bagging_temperature = 0.2,
                                        od_type='Iter',
                                        metric_period = 50,
                                        od_wait=50)
    model.fit(fit, 
          use_best_model=True,
          eval_set=val)
    
    model.save_model(f'../track_2_catboost/model_{i}.cbm')
    
    X_val['y_pred'] = model.predict_proba(X_val)[:, 1]
    X_val['target'] = y_val.copy()
    
    oof.append(X_val)
    
oof = pd.concat(oof)

/home/robin/anaconda3/envs/idao/lib/python3.8/site-packages/sklearn/model_selection/_split.py:292: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(
Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric.

0:	test: 0.7133409	best: 0.7133409 (0)	total: 163ms	remaining: 1m 21s
50:	test: 0.7271757	best: 0.7271757 (50)	total: 7.72s	remaining: 1m 7s
100:	test: 0.7301972	best: 0.7301972 (100)	total: 15.2s	remaining: 59.9s
150:	test: 0.7329697	best: 0.7329697 (150)	total: 22.4s	remaining: 51.8s
200:	test: 0.7354632	best: 0.7354632 (200)	total: 29.6s	remaining: 44.1s
250:	test: 0.7374176	best: 0.7374176 (250)	total: 37s	remaining: 36.7s
300:	test: 0.7390536	best: 0.7390536 (300)	total: 44.4s	remaining: 29.4s
350:	test: 0.7403514	best: 0.7403514 (350)	total: 51.8s	remaining: 22s
400:	test: 0.7414449	best: 0.7414449 (400)	total: 59.3s	remaining: 14.6s
450:	test: 0.7421370	best: 0.7421370 (450)	total: 1m 6s	remaining: 7.28s
499:	test: 0.7426854	best: 0.7426854 (499)	total: 1m 14s	remaining: 0us

bestTest = 0.7426853951
bestIteration = 499

<ipython-input-33-9adff4689012>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_val['y_pred'] = model.predict_proba(X_val)[:, 1]
<ipython-input-33-9adff4689012>:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_val['target'] = y_val.copy()
Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric.

0:	test: 0.7064387	best: 0.7064387 (0)	total: 154ms	remaining: 1m 16s
50:	test: 0.7252882	best: 0.7252882 (50)	total: 7.37s	remaining: 1m 4s
100:	test: 0.7281115	best: 0.7281115 (100)	total: 14.5s	remaining: 57.2s
150:	test: 0.7307505	best: 0.7307505 (150)	total: 21.6s	remaining: 49.9s
200:	test: 0.7334548	best: 0.7334548 (200)	total: 28.6s	remaining: 42.6s
250:	test: 0.7355205	best: 0.7355205 (250)	total: 35.7s	remaining: 35.4s
300:	test: 0.7375403	best: 0.7375403 (300)	total: 42.8s	remaining: 28.3s
350:	test: 0.7387131	best: 0.7387131 (350)	total: 50s	remaining: 21.2s
400:	test: 0.7398760	best: 0.7398760 (400)	total: 57.3s	remaining: 14.1s
450:	test: 0.7407053	best: 0.7407053 (450)	total: 1m 4s	remaining: 6.98s
499:	test: 0.7414705	best: 0.7414735 (498)	total: 1m 11s	remaining: 0us

bestTest = 0.7414735203
bestIteration = 498

Shrink model to first 499 iterations.

Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric.

0:	test: 0.7037107	best: 0.7037107 (0)	total: 146ms	remaining: 1m 12s
50:	test: 0.7221367	best: 0.7221367 (50)	total: 7.52s	remaining: 1m 6s
100:	test: 0.7257922	best: 0.7257922 (100)	total: 14.9s	remaining: 58.8s
150:	test: 0.7284815	best: 0.7284815 (150)	total: 22s	remaining: 50.9s
200:	test: 0.7317454	best: 0.7317454 (200)	total: 29.6s	remaining: 44s
250:	test: 0.7339926	best: 0.7339926 (250)	total: 37s	remaining: 36.7s
300:	test: 0.7354596	best: 0.7354596 (300)	total: 44.3s	remaining: 29.3s
350:	test: 0.7366855	best: 0.7366855 (350)	total: 51.5s	remaining: 21.9s
400:	test: 0.7378799	best: 0.7378799 (400)	total: 58.9s	remaining: 14.6s
450:	test: 0.7388857	best: 0.7388857 (450)	total: 1m 6s	remaining: 7.2s
499:	test: 0.7396386	best: 0.7396386 (499)	total: 1m 13s	remaining: 0us

bestTest = 0.7396386118
bestIteration = 499

Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric.

0:	test: 0.7123525	best: 0.7123525 (0)	total: 145ms	remaining: 1m 12s
50:	test: 0.7246024	best: 0.7246024 (50)	total: 7.54s	remaining: 1m 6s
100:	test: 0.7278365	best: 0.7278365 (100)	total: 15.4s	remaining: 1m
150:	test: 0.7307422	best: 0.7307422 (150)	total: 22.6s	remaining: 52.2s
200:	test: 0.7339295	best: 0.7339295 (200)	total: 30s	remaining: 44.6s
250:	test: 0.7362786	best: 0.7362786 (250)	total: 37.4s	remaining: 37.1s
300:	test: 0.7380310	best: 0.7380310 (300)	total: 44.8s	remaining: 29.6s
350:	test: 0.7394092	best: 0.7394092 (350)	total: 52.3s	remaining: 22.2s
400:	test: 0.7402065	best: 0.7402065 (400)	total: 59.8s	remaining: 14.8s
450:	test: 0.7410562	best: 0.7410562 (450)	total: 1m 7s	remaining: 7.3s
499:	test: 0.7417438	best: 0.7417511 (498)	total: 1m 14s	remaining: 0us

bestTest = 0.7417511397
bestIteration = 498

Shrink model to first 499 iterations.

Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric.

0:	test: 0.7100094	best: 0.7100094 (0)	total: 152ms	remaining: 1m 15s
50:	test: 0.7266691	best: 0.7266691 (50)	total: 7.61s	remaining: 1m 6s
100:	test: 0.7292462	best: 0.7292462 (100)	total: 14.9s	remaining: 58.8s
150:	test: 0.7328160	best: 0.7328160 (150)	total: 22.3s	remaining: 51.4s
200:	test: 0.7354169	best: 0.7354169 (200)	total: 29.6s	remaining: 44s
250:	test: 0.7376894	best: 0.7376894 (250)	total: 36.9s	remaining: 36.6s
300:	test: 0.7393427	best: 0.7393427 (300)	total: 44.4s	remaining: 29.3s
350:	test: 0.7408070	best: 0.7408070 (350)	total: 51.9s	remaining: 22s
400:	test: 0.7419233	best: 0.7419233 (400)	total: 59.3s	remaining: 14.6s
450:	test: 0.7428675	best: 0.7428675 (450)	total: 1m 6s	remaining: 7.23s
499:	test: 0.7436385	best: 0.7436385 (499)	total: 1m 13s	remaining: 0us

bestTest = 0.7436385143
bestIteration = 499

In [34]:
import joblib

!rm -f ./track_2/*.pkl

for ex in extractors:
    joblib.dump(ex, f'../track_2_catboost/{ex}.pkl')